### ISSUE TITLE
Permalink to results of a specific job

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#166]
The current URL does not change when a user inspects the differences between the original and reproduced document. It would be nice if there would be a URL that includes the specific job that a user is looking at, and optionally even opens that view, e.g.

- https://o2r.uni-muenster.de/#/erc/123abc/job/abc123
- https://o2r.uni-muenster.de/#/erc/123abc/job/abc123#result
- https://o2r.uni-muenster.de/#/erc/123abc/job/abc123#logs ?

**Comment by NJaku01** [comment]
The UI is using a HashRouter https://reactrouter.com/web/api/HashRouter at the moment. Therefore is it not possible to add a second hashtag to the route.  For this purpose it's useful to use the Browser Router https://reactrouter.com/web/api/BrowserRouter instead of the HashRouter. 
https://github.com/o2r-project/o2r-UI/blob/master/ui/src/components/app/App.js#L61
